import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Link, useLocation, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, CheckCircle2, Plus, RefreshCw, Send, ShieldAlert, UserPlus } from 'lucide-react'
import { accountApi, adminApi, beneficiaryApi, transactionApi, transferApi } from './api/bankingApi'
import { apiError } from './api/client'
import { authApi } from './api/authApi'
import { useAuth } from './context/AuthContext'
import type { Account, Beneficiary, Transaction, User } from './types/banking'
import { AccountCard, EmptyState, ErrorMessage, formatCurrency, formatDate, Loading, PageHeader, TransactionTable } from './components/Layout'

function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) { return <label className="field"><span>{label}</span><input {...props} /></label> }
function SelectField({ label, children, ...props }: React.SelectHTMLAttributes<HTMLSelectElement> & { label: string; children: React.ReactNode }) { return <label className="field"><span>{label}</span><select {...props}>{children}</select></label> }
function Submit({ children, loading }: { children: React.ReactNode; loading: boolean }) { return <button className="primary-button" disabled={loading}>{loading ? <><span className="spinner spinner-light" />Processing...</> : children}</button> }

export function LoginPage() {
  const { login, loading } = useAuth(); const navigate = useNavigate(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); try { await login(email, password); navigate('/') } catch (e) { setError(apiError(e)) } }
  return <AuthFrame title="Welcome back" subtitle="Sign in to your account."><form onSubmit={submit} className="auth-form">{error && <ErrorMessage message={error} />}<Field label="Email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /><Field label="Password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete="current-password" /><Submit loading={loading}>Sign in <ArrowRight size={17} /></Submit></form><p className="auth-switch">New here? <Link to="/register">Create an account</Link></p></AuthFrame>
}

export function RegisterPage() {
  const { register, loading } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ firstName: '', lastName: '', email: '', password: '' }); const [error, setError] = useState('')
  async function submit(event: FormEvent) { event.preventDefault(); setError(''); try { await register(form); navigate('/') } catch (e) { setError(apiError(e)) } }
  return <AuthFrame title="Open your account" subtitle="A modern, simple way to stay close to your money."><form onSubmit={submit} className="auth-form"><div className="form-grid">{(['firstName', 'lastName'] as const).map((key) => <Field key={key} label={key === 'firstName' ? 'First name' : 'Last name'} value={form[key]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} required />)}</div>{error && <ErrorMessage message={error} />}<Field label="Email address" type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /><Field label="Password" type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} required /><Submit loading={loading}>Create account <ArrowRight size={17} /></Submit></form><p className="auth-switch">Already registered? <Link to="/login">Sign in</Link></p></AuthFrame>
}

function AuthFrame({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { const capabilities = ['Account Management', 'Secure Transfers', 'Transaction History', 'Beneficiary Management']; return <div className="auth-page"><div className="auth-aside"><div className="brand"><span className="brand-mark">IB</span><span>Internet Banking System</span></div><div className="auth-aside-copy"><p className="eyebrow">Internet Banking System</p><h1>Secure banking, clearly organized.</h1><p>A secure digital banking platform for managing accounts, transactions and transfers.</p><ul className="capability-list">{capabilities.map((capability) => <li key={capability}><CheckCircle2 size={16} />{capability}</li>)}</ul></div><span className="aside-caption">Project banking workspace</span></div><section className="auth-panel"><div className="auth-box"><p className="eyebrow">Internet Banking System</p><h2>{title}</h2><p className="page-description">{subtitle}</p>{children}</div></section></div> }

export function DashboardPage() {
  const { user } = useAuth(); const navigate = useNavigate(); const [accounts, setAccounts] = useState<Account[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  useEffect(() => { Promise.resolve().then(async () => { try { const response = await accountApi.list(); setAccounts(response.data); if (response.data[0]) setTransactions((await transactionApi.list(response.data[0].accountNumber)).data) } catch (e) { setError(apiError(e)) } finally { setLoading(false) } }) }, [])
  const total = useMemo(() => accounts.reduce((sum, account) => sum + Number(account.balance), 0), [accounts])
  if (loading) return <Loading label="Loading your overview" />
  return <><PageHeader eyebrow="Dashboard" title={`Good morning, ${user?.firstName}.`} description="Your current account and transaction overview." action={<Link to="/accounts/new" className="primary-button"><Plus size={17} />Create account</Link>} />{error && <ErrorMessage message={error} />}<section className="metric-grid"><div className="metric-card metric-primary"><span>Total balance</span><strong>{formatCurrency(total)}</strong><small>Across {accounts.length} account{accounts.length === 1 ? '' : 's'}</small></div><div className="metric-card"><span>My accounts</span><strong>{accounts.length}</strong><small>Personal accounts</small></div><div className="metric-card"><span>Account status</span><strong>{accounts.filter((account) => account.status === 'ACTIVE').length}/{accounts.length}</strong><small>Active accounts</small></div></section><section className="section-heading"><div><p className="eyebrow">Your accounts</p><h2>Accounts at a glance</h2></div><Link to="/accounts" className="text-button">View all <ArrowRight size={16} /></Link></section>{accounts.length ? <div className="account-grid">{accounts.map((account) => <AccountCard key={account.accountId} account={account} onSelect={() => navigate(`/accounts/${account.accountNumber}`)} />)}</div> : <EmptyState title="No accounts yet" text="Create an account to see live balances here." />}<section className="section-heading"><div><p className="eyebrow">Latest activity</p><h2>Recent transactions</h2></div><Link to="/transactions" className="text-button">See history <ArrowRight size={16} /></Link></section><div className="panel"><TransactionTable transactions={transactions} compact /></div></>
}

export function AccountsPage() { const navigate = useNavigate(); const [accounts, setAccounts] = useState<Account[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { accountApi.list().then((r) => setAccounts(r.data)).catch((e) => setError(apiError(e))).finally(() => setLoading(false)) }, []); return <><PageHeader eyebrow="Accounts" title="My accounts" description="Keep track of every balance in one place." action={<Link to="/accounts/new" className="primary-button"><Plus size={17} />Open account</Link>} />{error && <ErrorMessage message={error} />}{loading ? <Loading label="Loading accounts" /> : accounts.length ? <div className="account-grid">{accounts.map((account) => <AccountCard key={account.accountId} account={account} onSelect={() => navigate(`/accounts/${account.accountNumber}`)} />)}</div> : <EmptyState title="No accounts found" text="Open an account to see it here." />}</> }

export function AccountDetailsPage() { const { accountNumber } = useParams(); const navigate = useNavigate(); const [account, setAccount] = useState<Account | null>(null); const [transactions, setTransactions] = useState<Transaction[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { if (!accountNumber) return; Promise.all([accountApi.get(accountNumber), transactionApi.list(accountNumber)]).then(([a, t]) => { setAccount(a.data); setTransactions(t.data) }).catch((e) => setError(apiError(e))).finally(() => setLoading(false)) }, [accountNumber]); if (loading) return <Loading label="Loading account" />; return <><PageHeader eyebrow="Account details" title={account?.accountNumber || 'Account'} description="Review the balance and latest activity for this account." action={<button className="secondary-button" onClick={() => navigate('/accounts')}>Back to accounts</button>} />{error && <ErrorMessage message={error} />}{account && <><div className="detail-hero"><div><span className={`status status-${account.status.toLowerCase()}`}>{account.status}</span><p className="eyebrow">{account.accountType}</p><strong>{formatCurrency(account.balance)}</strong><small>Available balance</small></div><div className="quick-actions"><Link to={`/accounts/${account.accountNumber}/deposit`} className="secondary-button">Deposit</Link><Link to={`/accounts/${account.accountNumber}/withdraw`} className="secondary-button">Withdraw</Link></div></div><div className="section-heading"><div><p className="eyebrow">Activity</p><h2>Transaction history</h2></div></div><div className="panel"><TransactionTable transactions={transactions} /></div></>}</> }

export function CreateAccountPage() { const navigate = useNavigate(); const [form, setForm] = useState({ accountNumber: '', accountType: 'SAVINGS' }); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { await accountApi.create(form); navigate('/accounts') } catch (err) { setError(apiError(err)) } finally { setLoading(false) } } return <><PageHeader eyebrow="Accounts" title="Open an account" description="Create a new savings account connected to your profile." /><div className="form-panel"><form onSubmit={submit} className="stack-form">{error && <ErrorMessage message={error} />}<Field label="Account number" placeholder="AC003" value={form.accountNumber} onChange={(e) => setForm({ ...form, accountNumber: e.target.value })} required /><SelectField label="Account type" value={form.accountType} onChange={(e) => setForm({ ...form, accountType: e.target.value })}><option>SAVINGS</option><option>CHECKING</option></SelectField><div className="form-actions"><Link to="/accounts" className="secondary-button">Cancel</Link><Submit loading={loading}>Create account <ArrowRight size={17} /></Submit></div></form></div></> }

export function MoneyActionPage({ kind }: { kind: 'deposit' | 'withdraw' }) { const { accountNumber } = useParams(); const navigate = useNavigate(); const [amount, setAmount] = useState(''); const [loading, setLoading] = useState(false); const [error, setError] = useState(''); async function submit(e: FormEvent) { e.preventDefault(); setLoading(true); setError(''); try { const request = { amount: Number(amount) }; if (kind === 'deposit') await accountApi.deposit(accountNumber!, request); else await accountApi.withdraw(accountNumber!, request); navigate(`/accounts/${accountNumber}`) } catch (err) { setError(apiError(err)) } finally { setLoading(false) } } return <><PageHeader eyebrow="Account action" title={kind === 'deposit' ? 'Deposit money' : 'Withdraw money'} description={`Update ${accountNumber} securely.`} /><div className="form-panel"><form onSubmit={submit} className="stack-form">{error && <ErrorMessage message={error} />}<Field label="Amount" type="number" min="0.01" step="0.01" placeholder="0.00" value={amount} onChange={(e) => setAmount(e.target.value)} required /><div className="form-actions"><Link to={`/accounts/${accountNumber}`} className="secondary-button">Cancel</Link><Submit loading={loading}>{kind === 'deposit' ? 'Process deposit' : 'Process withdrawal'} <ArrowRight size={17} /></Submit></div></form></div></> }

export function TransferPage() { const [accounts, setAccounts] = useState<Account[]>([]); const [form, setForm] = useState({ senderAccountNumber: '', receiverAccountNumber: '', amount: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const navigate = useNavigate(); useEffect(() => { accountApi.list().then((r) => { setAccounts(r.data); setForm((old) => ({ ...old, senderAccountNumber: r.data[0]?.accountNumber || '' })) }).catch((e) => setError(apiError(e))).finally(() => setLoading(false)) }, []); async function submit(e: FormEvent) { e.preventDefault(); setError(''); if (form.senderAccountNumber === form.receiverAccountNumber) return setError('Sender and receiver accounts must be different.'); setSaving(true); try { await transferApi.create({ senderAccountNumber: form.senderAccountNumber, receiverAccountNumber: form.receiverAccountNumber.trim(), amount: Number(form.amount) }); navigate('/transactions') } catch (err) { setError(apiError(err)) } finally { setSaving(false) } } if (loading) return <Loading label="Loading accounts" />; return <><PageHeader eyebrow="Transfer" title="Transfer money" description="Move money between accounts using the banking system." /><div className="form-panel"><form onSubmit={submit} className="stack-form">{error && <ErrorMessage message={error} />}<SelectField label="From account" value={form.senderAccountNumber} onChange={(e) => setForm({ ...form, senderAccountNumber: e.target.value })}>{accounts.map((a) => <option key={a.accountNumber} value={a.accountNumber}>{a.accountNumber} · {formatCurrency(a.balance)}</option>)}</SelectField><Field label="Receiver account number" placeholder="AC002" value={form.receiverAccountNumber} onChange={(e) => setForm({ ...form, receiverAccountNumber: e.target.value })} required /><Field label="Amount" type="number" min="0.01" step="0.01" placeholder="0.00" value={form.amount} onChange={(e) => setForm({ ...form, amount: e.target.value })} required /><p className="form-note">Transfers are recorded by the banking API as atomic account transactions.</p><Submit loading={saving}>Send transfer <Send size={17} /></Submit></form></div></> }

export function TransactionsPage() { const [accounts, setAccounts] = useState<Account[]>([]); const [selected, setSelected] = useState(''); const [transactions, setTransactions] = useState<Transaction[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { accountApi.list().then((r) => { setAccounts(r.data); setSelected(r.data[0]?.accountNumber || '') }).catch((e) => setError(apiError(e))).finally(() => setLoading(false)) }, []); useEffect(() => { if (selected) transactionApi.list(selected).then((r) => setTransactions(r.data)).catch((e) => setError(apiError(e))) }, [selected]); if (loading) return <Loading label="Loading transactions" />; return <><PageHeader eyebrow="Activity" title="Transaction history" description="Review deposits, withdrawals, and transfers by account." />{error && <ErrorMessage message={error} />}<div className="toolbar"><SelectField label="Account" value={selected} onChange={(e) => setSelected(e.target.value)}>{accounts.map((a) => <option key={a.accountNumber}>{a.accountNumber}</option>)}</SelectField><button className="secondary-button" onClick={() => selected && transactionApi.list(selected).then((r) => setTransactions(r.data))}><RefreshCw size={16} />Refresh</button></div><div className="panel"><TransactionTable transactions={transactions} /></div></> }

export function BeneficiariesPage() { const [beneficiaries, setBeneficiaries] = useState<Beneficiary[]>([]); const [form, setForm] = useState({ name: '', accountNumber: '', bankName: '' }); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); async function load() { try { setBeneficiaries((await beneficiaryApi.list()).data) } catch (e) { setError(apiError(e)) } finally { setLoading(false) } } useEffect(() => { load() }, []); async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(''); try { await beneficiaryApi.create(form); setForm({ name: '', accountNumber: '', bankName: '' }); await load() } catch (err) { setError(apiError(err)) } finally { setSaving(false) } } async function remove(id: number) { try { await beneficiaryApi.remove(id); await load() } catch (e) { setError(apiError(e)) } } return <><PageHeader eyebrow="Connections" title="Beneficiaries" description="Keep trusted recipient details close at hand." />{error && <ErrorMessage message={error} />}<div className="split-grid"><div className="form-panel"><h2>Add beneficiary</h2><form onSubmit={submit} className="stack-form"><Field label="Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><Field label="Account number" value={form.accountNumber} onChange={(e) => setForm({ ...form, accountNumber: e.target.value })} required /><Field label="Bank name" value={form.bankName} onChange={(e) => setForm({ ...form, bankName: e.target.value })} required /><Submit loading={saving}>Add beneficiary <UserPlus size={17} /></Submit></form></div><div className="panel"><div className="panel-heading"><h2>Saved beneficiaries</h2></div>{loading ? <Loading label="Loading beneficiaries" /> : beneficiaries.length ? <div className="beneficiary-list">{beneficiaries.map((item) => <div className="beneficiary-row" key={item.beneficiaryId}><div className="avatar avatar-small">{item.name[0]}</div><div><strong>{item.name}</strong><small>{item.accountNumber} · {item.bankName}</small></div><button className="icon-button danger" onClick={() => remove(item.beneficiaryId)} aria-label={`Remove ${item.name}`}>×</button></div>)}</div> : <EmptyState title="No beneficiaries" text="Add a recipient to make future transfers easier." />}</div></div></> }

export function ProfilePage() { const { user } = useAuth(); return <><PageHeader eyebrow="Account" title="Profile" description="Your authenticated banking profile." /><div className="profile-card"><div className="avatar avatar-large">{user?.firstName[0]}{user?.lastName[0]}</div><div><p className="eyebrow">{user?.role}</p><h2>{user?.firstName} {user?.lastName}</h2><p>{user?.email}</p><small>User ID {user?.userId}</small></div></div></> }

export function AdminPage() { const location = useLocation(); const [users, setUsers] = useState<User[]>([]); const [accounts, setAccounts] = useState<Account[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); useEffect(() => { Promise.all([adminApi.users(), adminApi.accounts(), adminApi.transactions()]).then(([u, a, t]) => { setUsers(u.data); setAccounts(a.data); setTransactions(t.data) }).catch((e) => setError(apiError(e))).finally(() => setLoading(false)) }, []); async function toggle(account: Account) { try { const result = account.status === 'ACTIVE' ? await adminApi.freeze(account.accountNumber) : await adminApi.unfreeze(account.accountNumber); setAccounts((items) => items.map((item) => item.accountNumber === account.accountNumber ? result.data : item)) } catch (e) { setError(apiError(e)) } } if (loading) return <Loading label="Loading administration" />; const view = location.pathname.split('/')[2] || 'overview'; return <><PageHeader eyebrow="Administration" title={view === 'overview' ? 'Control center' : `All ${view}`} description="Monitor the banking system and manage account status." />{error && <ErrorMessage message={error} />}{view === 'overview' && <><section className="metric-grid"><div className="metric-card metric-primary"><span>Total users</span><strong>{users.length}</strong><small>Registered profiles</small></div><div className="metric-card"><span>Total accounts</span><strong>{accounts.length}</strong><small>{accounts.filter((a) => a.status === 'ACTIVE').length} active</small></div><div className="metric-card"><span>Transactions</span><strong>{transactions.length}</strong><small>Recorded activity</small></div></section><div className="admin-callout"><ShieldAlert size={22} /><div><strong>Account oversight</strong><p>Freeze accounts only when required. Frozen accounts cannot transact.</p></div></div></>}{view === 'users' && <DataTable headers={['Name', 'Email', 'Role']} rows={users.map((u) => [u.firstName + ' ' + u.lastName, u.email, u.role])} />}{view === 'accounts' && <DataTable headers={['Account', 'Owner', 'Balance', 'Status', 'Action']} rows={accounts.map((a) => [a.accountNumber, a.accountType, formatCurrency(a.balance), a.status, <button className="small-button" onClick={() => toggle(a)}>{a.status === 'ACTIVE' ? 'Freeze' : 'Unfreeze'}</button>])} />}{view === 'transactions' && <TransactionTable transactions={transactions} />}</> }
function DataTable({ headers, rows }: { headers: string[]; rows: (React.ReactNode[])[] }) { return <div className="panel table-wrap"><table><thead><tr>{headers.map((h) => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{cell}</td>)}</tr>)}</tbody></table>{rows.length === 0 && <EmptyState title="Nothing to show" text="There are no records for this view." />}</div> }